### ISSUE TITLE
Not resolving Docker env vars

### ISSUE THREAD

**Issue by awoSYS** [arrowhead-tools/mgmt-tool-js#8]
I'm trying to use the management tool Docker container. I've successfully started the container and passed the core system addresses as environment variables:

```bash
> docker exec -it [containername] /bin/bash
> root@61d3a4c58730:/usr/src/app# env 
NODE_VERSION=9.9.0
HOSTNAME=61d3a4c58730
TERM=xterm
NPM_CONFIG_LOGLEVEL=warn
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/usr/src/app
SHLVL=1
HOME=/root
YARN_VERSION=1.5.1
ARROWHEAD_AUTH_URL=http://[custom host]:8445
ARROWHEAD_SR_URL=http://[custom host]:8443
ARROWHEAD_ORCH_URL=http://[custom host]:8441
_=/usr/bin/env
```

I've also verified that the core systems are up and running by opening the URLs given in the env vars in the browser and successfully reaching the swagger UIs.

However, if I open the management interface, it loads, but doesn't show any service in the registry, even though a couple have already been registered. Additionally, I see the following error in the browser console:

```
Error: Network Error
    exports createError.js:16
    onerror xhr.js:69
serviceRegistry.js:190:18
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://127.0.0.1:8443/serviceregistry/mgmt/grouped. (Reason: CORS request did not succeed).
```

I feel like the app doesn't resolve the URLs in the env vars but is rather falling back to the ones configured in the `.env` file. What am I doing wrong?

Thanks for your help!

**Comment by awoSYS** [comment]
Can anyone help here?

**Comment by tsvetlin** [comment]
Hey!

Can you please post your .env file?

**Comment by awoSYS** [comment]
I'm using the management tool **Docker** container, so I'm not having a `.env` file myself. I was referring to the `.env` file inside the container, to which the app seems to fall back instead of using the Docker env vars.

My `docker-compose.yml`:

```
...
ahfw-mgmt:
    image: svetlint/management-tool
    environment:
      - ARROWHEAD_SR_URL=http://[custom host]:8443
      - ARROWHEAD_ORCH_URL=http://[custom host]:8441
      - ARROWHEAD_AUTH_URL=http://[custom host]:8445
    ports:
      - 8499:5000
...
```

As shown in my initial comment, the env vars set via docker-compose are successfully passed to the container. However, the app seems to fall back to the `.env` file inside instead of using the Docker env vars.

Does that answer your question? Any ideas?

**Comment by mileippert** [comment]
I have had the same problem for a while and have debugged that issue up to a certain point where i cannot continue further.

To fix that request going to localhost, I had to add the environment variables with prefix REACT_APP_ with the domain as registered in our internal network. The variables you mentioned above contain the hostnames of the internal docker network and as such cannot be resolved from the outside.

```
  managementtool:
    container_name: management_tool
    image: svetlint/management-tool
    environment:
      - ARROWHEAD_SR_URL=https://serviceregistry:8443
      - ARROWHEAD_ORCH_URL=https://orchestrator:8441
      - ARROWHEAD_GK_URL=https://gatekeeper:8449
      - REACT_APP_ARROWHEAD_SR_URL=https://[custom dns alias]:8443
      - REACT_APP_ARROWHEAD_ORCH_URL=https://[custom dns alias]:8441
      - REACT_APP_ARROWHEAD_GK_URL=https://[custom dns alias]:8449
```

The issue I have now is that the request going to the Service Registry (/serviceregistry/mgmt/grouped) requires a SSL client certificate for sysop, which the management tool seems to be unable to provide with the request. My browser lists that request as failed with SSL_ERROR_BAD_CERT_ALERT.
